- name: Deploy Vault
  hosts: vault
  gather_facts: no
  become: yes

  tasks:

    - name: Create vault user
      ansible.builtin.user:
        name: vault
        shell: /bin/false

    - name: Install gpg
      ansible.builtin.apt:
        name: gpg

    - name: Add the HashiCorp GPG key
      ansible.builtin.shell: |
        wget -O- https://apt.releases.hashicorp.com/gpg \
        | gpg --dearmor \
        | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg >/dev/null
      args:
        creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

    - name: Add the official HashiCorp Linux repository
      ansible.builtin.shell: |
        echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" \
        | sudo tee /etc/apt/sources.list.d/hashicorp.list
      args:
        creates: /etc/apt/sources.list.d/hashicorp.list

    - name: Install vault
      ansible.builtin.apt:
        name: vault
        update_cache: yes

    - name: Copy configuration file
      become: yes
      become_user: vault
      ansible.builtin.copy:
        src: vault/initial_vault.hcl
        dest: /etc/vault.d/vault.hcl

    - name: Start vault service
      ansible.builtin.systemd:
        name: vault
        enabled: yes
        state: started

    - name: Initialize vault
      become: yes
      become_user: vault
      ansible.builtin.command:
        argv:
          - vault
          - operator
          - init
          - -key-shares=1
          - -key-threshold=1
      environment:
        VAULT_SKIP_VERIFY: true
        VAULT_ADDR: "https://traceit-07-i.comp.nus.edu.sg:8200"
      register: vault_output
      
    - name: Print unseal key and initial root token
      debug: 
        var: vault_output.stdout_lines