- name: Setup hosts
  hosts: all
  gather_facts: no
  become: yes

  tasks:

    - name: Add SSH authorized key
      ansible.posix.authorized_key:
        user: sadm
        state: present
        key: "{{ lookup('file', lookup('ansible.builtin.env','HOME') + '/.ssh/id_ed25519.pub') }}"
    
    - name: Configure passwordless sudo
      community.general.sudoers:
        name: passwordless-sudo
        state: present
        user: sadm
        runas: ALL
        commands: ALL
        nopassword: true

    - name: Update apt repository cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install required packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - acl
        - python3-pip

    - name: Install required python packages
      ansible.builtin.pip:
        name: "{{ item }}"
      loop:
        - hvac


    