- name: Unseal Vault
  hosts: vault
  gather_facts: no
  become: yes
  become_user: vault

  tasks:

    - name: Unseal vault
      ansible.builtin.uri:
        method: POST
        url: "https://traceit-07-i.comp.nus.edu.sg:8200/v1/sys/unseal"
        body:
          key: "{{ lookup('ansible.builtin.env', 'UNSEAL_KEY') }}"
        body_format: json
        headers:
          Content-Type: "application/json"
        validate_certs: no
        ca_path: /usr/local/share/ca-certificates/traceit-ca.crt
        client_cert: /opt/vault/tls/tls.crt
        client_key: /opt/vault/tls/tls.key
